FinalProj/src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Right__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Right</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProj/src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Right_Answer__c</fullName>
        <label>Right Answer</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FinalProj/src/classes/QuestionWrapper.cls
public class QuestionWrapper {
		public String questionText { get; set; }
		public Boolean rightAnswer { get; set; }
		public String UserAnswer { get; set; }
		public Boolean YesNoFlag { get; set; }
		public Boolean MultipleFlag { get; set; }

		//user answers for multiple questions
		public List<AnswerWrapper> AnswersForUser { get; set; }
		public Integer questionResult { get; set; }

		public QuestionWrapper(Question__c question) {
			questionText = question.Question_Text__c;
			
			if(question.Right_Answer__c == 'Yes'){
				rightAnswer = true;
			}
			else{
				rightAnswer = false;
			}
			
			
			parseQuestionByType(question);
		}

		private void parseQuestionByType(Question__c question) {
		AnswersForUser = new List<AnswerWrapper>();
			Map<ID, Schema.RecordTypeInfo> rt_Map = Question__c.sObjectType.getDescribe().getRecordTypeInfosById();

			if (rt_map.get(question.recordTypeID).getName().containsIgnoreCase('Multiple Choise')) {
				for (Answer__c answer :[SELECT Id, Text__c, Right__c, Question__c FROM Answer__c WHERE Question__c = :question.Id]) {
					AnswerWrapper wrapper = new AnswerWrapper(answer);
						wrapper.selected = false;
					AnswersForUser.add(wrapper);
				}
				YesNoFlag = false;
				MultipleFlag = true;
			}
			else {
				YesNoFlag = true;
				MultipleFlag = false;
			}
		}

		public Integer getResult(){
			questionResult = 0;
			if (YesNoFlag){
				if(UserAnswer != null){
					if (rightAnswer == Boolean.valueOf(UserAnswer)) {
						questionResult++;
					}
				}
			}
			else{
				for (AnswerWrapper answer : AnswersForUser) {
					if (answer.selected == true && answer.rightAnswer == true) {						
						questionResult++;
					}
					if(answer.selected == false && answer.rightAnswer == false){
						questionResult+=0;
					}
					
				}
			}
			return questionResult;
		}
	
	}