FinalProj/src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Right__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Right</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProj/src/classes/AnswerWrapper.cls
public class AnswerWrapper implements Comparable {
		public String questionText { get; set; }
		public Boolean rightAnswer { get; set; }
		public Boolean selected {get;set;}

		public AnswerWrapper(Answer__c answer) {
			questionText = answer.Text__c;
			rightAnswer = answer.Right__c;
		}

		public Integer compareTo(Object compareTo) {
			AnswerWrapper compareToEmp = (AnswerWrapper) compareTo;
			if (questionText == compareToEmp.questionText) return 0;
			if (questionText > compareToEmp.questionText) return 1;
			return - 1;
		}
	}