FinalProj/src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Required_Question__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required Question</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Right_Answer__c</fullName>
        <label>Right Answer</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FinalProj/src/objects/TestToQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>QuestionTests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipName>QuestionTests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Question</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Test Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProj/src/objects/TestToUser__c.object
<CustomObject>
    <fields>
        <fullName>Result__c</fullName>
        <defaultValue>-1</defaultValue>
        <label>Result</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Test Users</relationshipLabel>
        <relationshipName>UserTests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserTests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test User</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Test User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProj/src/classes/TestWrapper.cls
public class TestWrapper {
		public String Name { get; set; }
		public DateTime Avalible_From { get; set; }
		public DateTime Avalible_To { get; set; }
		public String Guide { get; set; }
		public Decimal Time_Limit { get; set; }
		public Integer CurrentNum { get; set; }
		public Integer Result { get; set; }
		public List<QuestionWrapper> Questions { get; set; }
		public Boolean RenderResultPage {get;set;}
		public Boolean RenderQuestions { get; set; }

		public TestWrapper(Test__c testRecord)
		{
			Name = testRecord.Name;
			Avalible_From = testRecord.Avalible_From__c;
			Avalible_To = testRecord.Avalible_To__c;
			Guide = testRecord.Guide__c;
			Time_Limit = testRecord.Time_Limit__c;
			CurrentNum = 0;
			
			getTestQuestions(testRecord.Id);
			RenderResultPage = false;
			RenderQuestions = true;
		}


		private void getTestQuestions(Id testRecord) {
			Result = 0;
			Questions = new List<QuestionWrapper> ();
			List<Id> testQuestions = new List<Id> ();
			for (TestToQuestion__c testToquestion :[SELECT Id, Question__c, Test__c FROM TestToQuestion__c WHERE Test__c = :testRecord]) {
				testQuestions.add(testToquestion.Question__c);
			}
			for (Question__c question :[SELECT Id, Name, Question_Text__c, Required_Question__c,RecordTypeId, Right_Answer__c FROM Question__c WHERE Id IN :testQuestions]) {
				Questions.add(new QuestionWrapper(question));
			}
		}

		public void NextQuestion() {		
			if (CurrentNum < Questions.size() - 1){
				CurrentNum++;
			}
			else{
				calculateResults();
				RenderResultPage = true;
				RenderQuestions = false;
				finishTest();
			}
			
		}

		public void calculateResults() {
			for(QuestionWrapper question : Questions){
				Result += question.getResult();
			}
		}

		public void finishTest(){
			String userid = UserInfo.getUserId();
			List<TestToUser__c> tUser = [SELECT Id, Test__c, User__c, Result__c FROM TestToUser__c WHERE User__c = :userid AND Result__c = -1];
			tUser[0].Result__c = Result;
			Database.update(tUser);
		}

	}