FinalProj/src/objects/TestToUser__c.object
<CustomObject>
    <fields>
        <fullName>Result__c</fullName>
        <defaultValue>-1</defaultValue>
        <label>Result</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipLabel>Test Users</relationshipLabel>
        <relationshipName>UserTests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserTests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test User</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Test User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FinalProj/src/classes/DataHelper.cls
public class DataHelper {
		public  String userid;
		public List<TestWrapper> setAvalibleTests() {
			
			List<TestWrapper> AvalibleTests = new List<TestWrapper>();
			for (Test__c testRec : getNowAvalibleTests()) {
				if (testRec != null) {
					AvalibleTests.add(new TestWrapper(testRec));
				}
			}
			
			return AvalibleTests;
		}

		private  List<Test__c> getNowAvalibleTests() {
			List<Id> TestsForUser = new List<Id>();
			List<Test__c> avalibleTests = new List<Test__c>();

			for (TestToUser__c testUser :[SELECT Id, Test__c, User__c, Result__c FROM TestToUser__c WHERE User__c = :userid AND Result__c = -1]) {
				TestsForUser.add(testUser.Test__c);
			}

			DateTime now = DateTime.now();
			for (Test__c testRec :[SELECT Id, Name, Avalible_From__c, Avalible_To__c, Guide__c, Time_Limit__c FROM Test__c WHERE Id IN :TestsForUser AND Avalible_From__c <= :now AND Avalible_To__c > :now]) {
				avalibleTests.add(testRec);
			}
		
			return avalibleTests;
		}
	}